/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clothingstoreassessment.Views;

import clothingstoreassessment.Clothing;
import clothingstoreassessment.DBManager;
import clothingstoreassessment.Footwear;
import clothingstoreassessment.Product;
import clothingstoreassessment.Staff;
import static javax.swing.text.StyleConstants.Size;

/**
 *
 * @author 30207193
 */
public class EditProduct extends javax.swing.JFrame {
    private Staff loggedInStaff;
    private Product selectedProduct;
    
    /**
     * Creates new form EditProduct
     */
    public EditProduct(Staff staff, Product product) {
         loggedInStaff = staff;
        selectedProduct = product;
        
        
        
        initComponents();
        
                txtId.setText(String.valueOf(selectedProduct.getProductId()) );
                txtId.setEnabled  (false);
                txtPrice.setText(String.valueOf(selectedProduct.getPrice()) );
                txtStock.setText(String.valueOf(selectedProduct.getStockLevel()) );
  
                 if(selectedProduct.getClass().getName().equals("models.Clothing"))
        {
            lblAdditional.setText("Measurement?");
            Clothing selectedClothing = (Clothing)selectedProduct;
            txtAdditional.setText(String.valueOf(selectedClothing.getMeasurement()));
        }
        else
        {
            lblAdditional.setText("Size:");
            Footwear selectedFootwear = (Footwear)selectedProduct;
            txtAdditional.setText(String.valueOf(selectedFootwear.getSize()));
        }
        
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnReturn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblAdditional = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        txtPrice = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        txtStock = new javax.swing.JTextField();
        txtAdditional = new javax.swing.JTextField();
        lblMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("ID:");

        jLabel3.setText("Name:");

        btnReturn.setText("RETURN TO Product MENU");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        jLabel4.setText("Price: £");

        jLabel1.setText("EDIT EXISTING Product");

        jLabel5.setText("Stock Level:");

        lblAdditional.setText("Measurement: ");

        btnSubmit.setText("SUBMIT");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnClear.setText("CLEAR CHANGES");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReturn)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(lblAdditional))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtAdditional, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtPrice, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtId, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtStock, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnClear)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblMessage)
                                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnReturn)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdditional)
                    .addComponent(txtAdditional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(btnSubmit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClear)
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
       ProductMenu productMenu = new ProductMenu(loggedInCustomer);
        this.dispose();
        productMenu.setVisible(true);
    }//GEN-LAST:event_btnReturnActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        if(!txtId.getText().isEmpty() && !txtName.getText().isEmpty() && !txtPrice.getText().isEmpty()
            && !txtStock.getText().isEmpty() && !txtAdditional.getText().isEmpty()
            && !txtAdditional.getText().isEmpty() && !txtPrice.getText().isEmpty())
        {
            String name = txtId.getText();
            double price = 00.00;
          int stock = 0;
         
            
            try
            {
               price = Double.parseDouble(txtPrice.getText());
            }
            catch(Exception ex)
            {
                lblMessage.setText("Priced in wrong format");
                return;
            }

            try
            {
                stock = Integer.parseInt(txtStock.getText());
            }
            catch(Exception ex)
            {
                lblMessage.setText("Stock in wrong format");
                return;
            }

            if(selectedProduct.getClass().getName().equals("models.Clothing"))
            {
                try
                {
                    String measurement = txtAdditional.getText();
                    Clothing clothing = new Clothing(selectedProduct.getProductId(),name, price, stock, measurement);

                    DBManager db = new DBManager();
                    db.updateProduct(clothing);
                    lblMessage.setText("Clothing Item updated successfully");

                    selectedProduct = clothing;
                }
                catch(Exception ex)
                {
                    lblMessage.setText(" in wrong format");
                }
            }
            else if (selectedProduct.getClass().getName().equals("models.Footwear"))
            {
                String size = txtAdditional.getText();
                Footwear newFootwear = new Footwear(selectedProduct.getProductId(),productName, price, stockLevel,Size );

                DBManager db = new DBManager();
                db.updateProduct(newFootwear);
                lblMessage.setText("Footwear updated successfully");

                selectedProduct = newFootwear;
            }
        }
        else
        {
            lblMessage.setText("Please complete all fields");
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
  //      txtId.setText(selectedProduct.getId());
        txtName.setText((selectedProduct.getProductName()));
        txtPrice.setText(String.valueOf (selectedProduct.getPrice()));
        txtStock.setText(String.valueOf(selectedProduct.getStockLevel()));
        
      
        if(selectedProduct.getClass().getName().equals("models.Clothing"))
        {
            lblAdditional.setText("Measurement:");
            Clothing selectedClothing = (Clothing)selectedProduct;
            txtAdditional.setText(String.valueOf(selectedClothing.getMeasurement()));
        }
        else
        {
            lblAdditional.setText("Water Type:");
            Footwear selectedFish = (Footwear)selectedProduct;
            txtAdditional.setText(String.valueOf(selectedFish.getSize()));
        }

        lblMessage.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              //  new EditProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblAdditional;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JTextField txtAdditional;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
